apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: gitlab-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: gitlab-template
    parameters:
    - name: APP_NAME
      description: A GitLab Deployment Name
      displayName: AppName
      required: true
      value: gitlab-test-deploy
    - name: NAMESPACE
      description: A Namespace Name
      displayName: Namespace
      required: true
      value: default
    - name: STORAGE
      description: Storage size
      displayName: Storage
      required: true
      value: 30Gi
