apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: gitlab-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: gitlab-template
    parameters:
    - name: APP_NAME
      value: gitlab-test-deploy
    - name: NAMESPACE
      value: default
    - name: STORAGE
      value: 30Gi
    - name: SERVICE_TYPE
      value: LoadBalancer
