apiVersion: tmax.io/v1
kind: Template
metadata:
  name: mariadb-template
  namespace: default
shortDescription: mariadb-deployment
imageUrl: https://upload.wikimedia.org/wikipedia/commons/c/c9/MariaDB_Logo.png
longDescription: mariadb-deployment
provider: tmax
tags:
- db
- mariadb
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - port: 3306
    selector:
      app: ${APP_NAME}
      tier: mariadb
    clusterIP: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    #storageClassName: manual
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
    namespace: ${NAMESPACE}
  type: Opaque
  stringData:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    database: ${MYSQL_DATABASE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-mariadb
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: mariadb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: mariadb
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/mariadb:10.2
          name: mariadb
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: database
          ports:
          - containerPort: 3306
            name: mariadb
          volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql/data
        volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
parameters:
- name: APP_NAME
  description: Application name
- name: NAMESPACE
  description: Application namespace
- name: DB_STORAGE
  description: Storage size for DB
- name: MYSQL_USER
  description: MysqlUser
- name: MYSQL_PASSWORD
  description: MysqlPassword
- name: MYSQL_DATABASE
  description: MysqlDatabase
plans:
- name: mariadb-plan1
  description: mariadb
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAMESPACE: default
          DB_STORAGE: 5Gi
          APP_NAME: mariadb-deploy
          MYSQL_USER: root1
          MYSQL_PASSWORD: tmax@23
          MYSQL_DATABASE: root1
- name: mariadb-plan2
  description: mariadb
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAMESPACE: default
          DB_STORAGE: 30Gi
          APP_NAME: mariadb-deploy
          MYSQL_USER: root1
          MYSQL_PASSWORD: tmax@23
          MYSQL_DATABASE: root1
