apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mariadb-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: mariadb-template
    parameters:
    - name: APP_NAME
      value: mariadb-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "20Gi"
    - name: MYSQL_USER
      value: root1
    - name: MYSQL_PASSWORD
      value: tmax@23
    - name: MYSQL_DATABASE
      value: root1
