apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.tmax.io
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: images
    singular: image
    kind: Image
    shortNames:
    - img
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec]
      properties:
        spec:
          type: object
          required: [name, version, registry]
          description: Image information
          properties:
            name:
              type: string
            version:
              type: string
            registry:
              type: string
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: ImageName
    type: string
    description: Image Name
    JSONPath: .spec.name
  - name: ImageVersion
    type: string
    description: Image Version or Tag
    JSONPath: .spec.version
  - name: Registry
    type: string
    description: Registry URL
    JSONPath: .spec.registry
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp