apiVersion: tmax.co.kr/v1
kind: Registry
metadata: 
  name: tmax-registry
  namespace: hypercloud-system
  labels:
    obj: registry
spec:
  image: 192.168.6.110:5000/registry:b004
  description: test
  storageSize: "10Gi"
  loginId: tmax
  loginPassword: tmax123
