apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: registries
    singular: registry
    kind: Registry
    shortNames:
    - reg
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec]
      properties:
        spec:
          type: object
          required: [image, loginId, loginPassword, storageSize]
          description: registry information
          properties:
            image:
              type: string
            description:
              type: string
            loginId:
               type: string
            loginPassword:
               type: string
            storageSize:
              type: string
        status:
          type: object
          required: [phase]
          properties:
             message:
               type: string
             phase:
               type: string
               enum: [Creating, Running, Failed]
             reason:
               type: string
  additionalPrinterColumns:
  - name: Image
    type: string
    description: Registry Image
    JSONPath: .spec.image
  - name: Capacity
    type: string
    description: Registry PVC Size
    JSONPath: .spec.storageSize
  - name: Status
    type: string
    description: Registry Status
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
