apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: jenkins-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: jenkins-template
    parameters:
    - name: APP_NAME
      value: jenkins-test-deploy
    - name: NAMESPACE
      value: default
    - name: STORAGE
      value: 10Gi
    - name: SERVICE_TYPE
      value: LoadBalancer
