apiVersion: tmax.io/v1
kind: Template
metadata:
  name: postgresql-template
shortDescription: postgresql-deployment
imageUrl: https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg
longDescription: postgresql-deployment
provider: tmax
tags:
- db
- postgresql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - port: 5432
    selector:
      app: ${APP_NAME}
      tier: postgresql
    clusterIP: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    #storageClassName: manual
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
    namespace: ${NAMESPACE}
  type: Opaque
  stringData:
    user: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    database: ${POSTGRESQL_DATABASE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-postgresql
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: postgresql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: postgresql
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/postgresql:9.6
          name: postgresql
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: database
          ports:
          - containerPort: 5432
            name: postgresql
          volumeMounts:
          - name: postgresql-persistent-storage
            mountPath: /var/lib/pgsql/data
        volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
plans:
- name: postgresql-plan1
  description: postgresql
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          APP_NAME: postgresql-deploy
          NAMESPACE: default
          DB_STORAGE: 5Gi
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: tmax@23
          POSTGRESQL_DATABASE: root
- name: postgresql-plan2
  description: postgresql
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          APP_NAME: postgresql-deploy
          NAMESPACE: default
          DB_STORAGE: 30Gi
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: tmax@23
          POSTGRESQL_DATABASE: root
