apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nodejs-cicd-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: nodejs-cicd-template
    parameters:
    - description: A Pipeline Name
      displayName: PipelineName
      name: PIPELINE_NAME
      required: true
      value: nodejs-cicd-pipeline
    - description: A Namespace Name
      displayName: Namespace
      name: NAMESPACE
      required: true
      value: default
