apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: redis-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: redis-template
    parameters:
    - name: APP_NAME
      value: redis-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "20Gi"
    - name: DATABASE_SERVICE_NAME
      value: redis
    - name: REDIS_PASSWORD
      value: tmax@23
