apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: generate-and-deploy-using-kubectl
  annotations:
    template-version: '1.0.0'
    tested-operator-version: '4.1.0.23'
spec:
  params:
  - name: app-name
    description: Deployment name
  - name: port
    description: Port for was deployment
  - name: replica
    description: Number of replica
  - name: image-url
    description: Updated image url:tag
    default: $(inputs.resources.image.url)
  - name: deploy-cfg-name
    description: Deployment configmap name
    default: ""
  - name: deploy-env-json
    description: Deployment environment variable in JSON object form
    default: "{}"
  resources:
    inputs:
    - name: image
      type: image
  steps:
  - name: create-yaml
    image: 192.168.6.110:5000/cicd-util:1.0.0
    imagePullPolicy: Always
    command:
    - "make-deployment"
    args:
    - $(inputs.params.app-name)
    - $(inputs.params.replica)
    - $(inputs.params.image-url)
    - $(inputs.params.port)
    volumeMounts:
    - mountPath: /generate
      name: generate
    env:
    - name: CONFIGMAP_NAME
      value: $(inputs.params.deploy-cfg-name)
    - name: DEPLOY_ENV_JSON
      value: $(inputs.params.deploy-env-json)
  - name: run-kubectl
    image: 192.168.6.110:5000/cicd-util:1.0.0
    command:
    - "kubectl"
    args:
    - apply
    - -f
    - /generate/deployment.yaml
    volumeMounts:
    - mountPath: /generate
      name: generate
  volumes:
  - emptyDir: {}
    name: generate

