apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: tomcat-cicd-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: tomcat-cicd-template
    parameters:
    - name: APP_NAME
      value: tomcat-sample-app
    - name: NAMESPACE
      value: default
    - name: SERVICE_ACCOUNT_NAME
      value: tutorial-service
    - name: GIT_URL
      value: https://github.com/cqbqdd11519/TomcatMavenApp
    - name: GIT_REV
      value: master
    - name: IMAGE_URL
      value: 192.168.6.110:5000/tomcat-sample:latest
    - name: REGISTRY_SECRET
      value: ''
    - name: REGISTRY_ID
      value: ''
    - name: REGISTRY_PW
      value: ''
    - name: WAS_PORT
      value: 8080
    - name: SERVICE_TYPE
      value: LoadBalancer
    - name: PACKAGE_SERVER_URL
      value: ''
