apiVersion: v1
kind: Namespace
metadata:
  name: hypercloud4-system

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: hypercloud4-system-quota
  namespace: hypercloud4-system
spec:
  hard:
    limits.cpu: "2"
    limits.memory: "10Gi"
    requests.storage: "20Gi"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypercloud4-admin
  namespace: hypercloud4-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypercloud4-admin
  namespace: hypercloud4-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hypercloud4-admin
subjects:
  - kind: ServiceAccount
    name: hypercloud4-admin
    namespace: hypercloud4-system
roleRef:
  kind: ClusterRole
  name: hypercloud4-admin
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - user
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [userInfo, status]
      properties:
        userInfo:
          type: object
          required: [name, password, email, phone]
          description: UserInfo contains user information
          properties:
            name:
              type: string
            password:
              type: string
            passwordSalt:
              type: string
            email:
              type: string
            phone:
              type: string 
            department:
              type: string
            position:
              type: string
            description:
              type: string
        status:
          type: string
          description: Status defines whether the user is active or blocked
          enum: [active, blocked]
          
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tokens.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: tokens
    singular: token
    kind: Token
    shortNames:
    - token
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:     
        type: object
        required: [accessToken, refreshToken]
        description: Token contains encrypted access token and refresh token
        properties:
          accessToken:
            type: string
          refreshToken:
            type: string
            
---

apiVersion: tmax.co.kr/v1
kind: User
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tmax.co.kr/v1","kind":"User","metadata":{"annotations":{},"labels":{"app":"test","encrypted":"f"},"name":"admin-tmax.co.kr"},"status":"active","userInfo":{"department":"CK2-4","description":"For test","email":"admin@tmax.co.kr","name":"Admin","password":"c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec","phone":"010-5730-8221","position":"developer"}}
  creationTimestamp: "2020-03-13T05:14:36Z"
  generation: 3
  labels:
    app: test
    encrypted: t
  name: admin-tmax.co.kr
  resourceVersion: "8268758"
  selfLink: /apis/tmax.co.kr/v1/users/admin-tmax.co.kr
  uid: eca984a0-0a99-4329-b826-6fc9ec973cfa
status: active
userInfo:
  department: CK2-4
  description: For test
  email: admin@tmax.co.kr
  name: Admin
  password: 3da13df61dc87ba605d441920abf00a3d30fd8b32c109670e04236e12ba668b7
  passwordSalt: 2ba19dcc-bb56-484b-b426-53d19dced859
  phone: 010-5730-8221
  position: developer
  
---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: ClusterRoleBinding
metadata:
  name: admin
subjects:
- kind: User
  name: admin@tmax.co.kr # Name is case sensitive
roleRef:
  kind: ClusterRole  #this must be Role or ClusterRole
  name: cluster-admin  # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: templates
    singular: template
    kind: Template
    shortNames:
    - tp
  preserveUnknownFields: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        labels:
          additionalProperties:
            type: string
          type: object
        message:
          type: string
        metadata:
          properties:
            generateName:
              type: string
            name:
              type: string
          type: object
        objects:
          items:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          type: array
        parameters:
          items:
            properties:
              description:
                type: string
              displayName:
                type: string
              from:
                type: string
              generate:
                type: string
              name:
                type: string
              required:
                type: boolean
              value:
                type: string
            required:
            - name
            type: object
          type: array

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templateinstances.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: templateinstances
    singular: templateinstance
    kind: TemplateInstance
    shortNames:
    - ti
  preserveUnknownFields: true
  validation:
    openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              generateName:
                type: string
              name:
                type: string
            type: object
          spec:
            type: object
            properties:
              requester:
                type: object
                properties:
                  extra:
                    type: object
                    #x-kubernetes-embedded-resource: true
                    x-kubernetes-preserve-unknown-fields: true
                  groups:
                    type: array
                    items:
                      type: string
                  uid:
                    type: string
                  username:
                    type: string
              secret:
                type: object
                properties:
                  name:
                    type: string
              template:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  message:
                    type: string
                  metadata:
                    properties:
                      generateName:
                        type: string
                      name:
                        type: string
                    type: object
                  objects:
                    items:
                      type: object
                      x-kubernetes-embedded-resource: true
                      x-kubernetes-preserve-unknown-fields: true
                    type: array
                  parameters:
                    items:
                      properties:
                        description:
                          type: string
                        displayName:
                          type: string
                        from:
                          type: string
                        generate:
                          type: string
                        name:
                          type: string
                        required:
                          type: boolean
                        value:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
          status:
            type: object
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                    - type
                  type: object
                type: array
              objects:
                items:
                  properties:
                    ref:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        fieldPath:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                        resourceVersion:
                          type: string
                        uid:
                          type: string
                  required:
                  - ref
                  type: object
                type: array
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: registries
    singular: registry
    kind: Registry
    shortNames:
    - reg
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec]
      properties:
        spec:
          type: object
          required: [image, loginId, loginPassword, storageSize]
          description: registry information
          properties:
            image:
              type: string
            description:
              type: string
            loginId:
               type: string
            loginPassword:
               type: string
            storageSize:
              type: string
        status:
          type: object
          required: [phase]
          properties:
             message:
               type: string
             phase:
               type: string
               enum: [Creating, Running, Failed]
             reason:
               type: string
  additionalPrinterColumns:
  - name: Image
    type: string
    description: Registry Image
    JSONPath: .spec.image
  - name: Capacity
    type: string
    description: Registry PVC Size
    JSONPath: .spec.storageSize
  - name: Status
    type: string
    description: Registry Status
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp