apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: hypercloud4-system
type: Opaque
data:
  ROOT_PASSWORD: dG1heA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: hypercloud4-system
data:
  initdb.sql: |
    create table metering.metering (id varchar(32) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,public_ip int,private_ip int,metering_time timestamp,status varchar(255),primary key (id));
    create table metering.metering_hour (id varchar(32) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,public_ip int,private_ip int,metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    create table metering.metering_day (id varchar(32) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,public_ip int,private_ip int,metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    create table metering.metering_month (id varchar(32) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,public_ip int,private_ip int,metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    create table metering.metering_year (id varchar(32) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,public_ip int,private_ip int,metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));