apiVersion: tmax.io/v1
kind: Template
metadata:
  name: apache-cicd-template
  namespace: default
imageUrl: https://upload.wikimedia.org/wikipedia/commons/4/45/Apache_HTTP_server_logo_%282016%29.png
provider: tmax
recommend: false
shortDescription: Apache CI/CD Template
longDescription: Apache CI/CD Template
tags:
- was
- apache
plans:
- bindable: false
  description: apache
  name: apache-plan1
parameters:
- name: PIPELINE_NAME
  displayName: PipelineName
  description: Pipeline name
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Application namespace
  required: true
objects:
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: ${PIPELINE_NAME}
    namespace: ${NAMESPACE}
  spec:
    resources:
    - name: source-repo
      type: git
    - name: image
      type: image
    params:
    - name: app-name
      type: string
      description: Application name
    - name: replica
      type: string
      description: Number of replica
      default: "1"
    - name: port
      type: string
      description: Application port
      default: "8080"
    tasks:
    - name: build-source
      taskRef:
        name: s2i
        kind: ClusterTask
      params:
      - name: BUILDER_IMAGE
        value: 192.168.6.110:5000/s2i-apache:2.4
      resources:
        inputs:
        - name: source
          resource: source-repo
        outputs:
        - name: image
          resource: image
    - name: scan-and-sign-image
      taskRef:
        name: analyze-image-vulnerabilities
        kind: ClusterTask
      resources:
        inputs:
        - name: scanned-image
          resource: image
          from:
          - build-source
      params:
      - name: image-url
        value: $(tasks.build-source.results.image-url)
    - name: deploy
      taskRef:
        name: generate-and-deploy-using-kubectl
        kind: ClusterTask
      runAfter:
      - scan-and-sign-image
      resources:
        inputs:
        - name: image
          resource: image
      params:
      - name: app-name
        value: $(params.app-name)
      - name: replica
        value: $(params.replica)
      - name: port
        value: $(params.port)
      - name: image-url
        value: $(tasks.build-source.results.image-url)
