apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: apache-cicd-template-instance
  namespace: default
spec:
  template:
    metadata:
      name: apache-cicd-template
    parameters:
    - name: APP_NAME
      value: apache-sample-app
    - name: NAMESPACE
      value: default
    - name: SERVICE_ACCOUNT_NAME
      value: tutorial-service
    - name: GIT_URL
      value: https://github.com/microsoft/project-html-website
    - name: GIT_REV
      value: master
    - name: IMAGE_URL
      value: 192.168.6.110:5000/apache-sample:latest
    - name: WAS_PORT
      value: 8080
    - name: SERVICE_TYPE
      value: LoadBalancer
