apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.tmax.io
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - user
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      # required 'metadata.labels.encrypted: f'
      # metadata.name ex) admin-tmax.co.kr -> @ Must be entered as -
      # userInfo.email ex) admin@tmax.co.kr -> Email and name should be the same
      # The user controller will encrypt the password and update label 'encrypted: t'
      type: object
      required: [userInfo, status]
      properties:
        userInfo:
          type: object
          required: [name, password, email, phone]
          description: UserInfo contains user information
          properties:
            name:
              type: string
            password:
              type: string
            passwordSalt:
              type: string
              description: do not enter
            email:
              type: string
            phone:
              type: string 
            department:
              type: string
            position:
              type: string
            description:
              type: string
        status:
          type: string
          description: Status defines whether the user is active or blocked
          enum: [active, blocked]