apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: verdaccio-package-server-instance
  namespace: default
spec:
  template:
    metadata:
      name: verdaccio-package-server
    parameters:
    - name: DEPLOY_NAME
      value: verdaccio-private-1
    - name: NAMESPACE
      value: default
    - name: STORAGE
      value: 10Gi

