apiVersion: tmax.io/v1
kind: Template
metadata:
  name: mongodb-template
  namespace: default
shortDescription: mongodb-deployment
imageUrl: https://upload.wikimedia.org/wikipedia/en/4/45/MongoDB-Logo.svg
longDescription: mongodb-deployment
provider: tmax
tags:
- db
- mongodb
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - port: 27017
    selector:
      app: ${APP_NAME}
      tier: mongodb
    clusterIP: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    #storageClassName: manual
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
    namespace: ${NAMESPACE}
  type: Opaque
  stringData:
    user: ${MONGODB_USER}
    password: ${MONGODB_PASSWORD}
    database: ${MONGODB_DATABASE}
    adminpassword: ${MONGODB_ADMIN_PASSWORD}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-mongodb
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: mongodb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: mongodb
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/mongodb:2.6
          name: mongodb
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: user
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: database
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: adminpassword
          ports:
          - containerPort: 27017
            name: mongodb
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /var/lib/mongodb/data
        volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
parameters:
- name: APP_NAME
  displayName: AppName
  description: Application name
  required: true
- name: NAMESPACE
  displayName: Namespace
  required: true
  description: Application namespace
- name: DB_STORAGE
  displayName: DBStorage
  description: Storage size for DB
  required: true
- name: MONGODB_USER
  displayName: MongoDBUser
  description: MongoDBUser
  required: true
- name: MONGODB_PASSWORD
  displayName: MongoDBPassword
  description: MongoDBPassword
  required: true
- name: MONGODB_DATABASE
  displayName: MongoDBDatabase
  description: MongoDBDatabase
  required: true
- name: MONGODB_ADMIN_PASSWORD
  displayName: MongoDBAdminPassword
  description: MongoDBAdminPassword
  required: true
plans:
- name: mongodb-plan1
  description: mongodb
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAMESPACE: default
          DB_STORAGE: 5Gi
          APP_NAME: mongodb-deploy
          MONGODB_USER: root
          MONGODB_PASSWORD: root
          MONGODB_DATABASE: root
          MONGODB_ADMIN_PASSWORD: root
- name: mongodb-plan2
  description: mongodb
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          NAMESPACE: default
          DB_STORAGE: 30Gi
          APP_NAME: mongodb-deploy
          MONGODB_USER: root
          MONGODB_PASSWORD: root
          MONGODB_DATABASE: root
          MONGODB_ADMIN_PASSWORD: root
