apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: tibero-template-instance
  namespace: default
  annotations:
    template-version: 1.0.0
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: tibero-template
    parameters:
    - name: APP_NAME
      value: tibero-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "10Gi"
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: MASTER_USER
      value: tibero
    - name: MASTER_PASSWORD
      value: tibero
    - name: TCS_INSTALL
      value: 1
    - name: TCS_SID
      value: tibero
    - name: TB_SID
      value: tibero
    - name: TCS_PORT
      value: 8629
